export const API_FIELDS = {
  Id: "id",
  UppercaseId: "ID",
  Email: "email",
  Password: "password",
  Name: "name",
  Username: "username",
  User: "user",
  Error: "error",
  Message: "message",
  UserId: "userId",
  SnakeCaseUserId: "user_id",
  UppercaseUserId: "UserID",
  PostId: "postId",
  SnakeCasePostId: "post_id",
  UppercasePostId: "PostID",
  AuthorId: "authorId",
  SnakeCaseAuthorId: "author_id",
  AuthorName: "authorName",
  SnakeCaseAuthorName: "author_name",
  UppercaseAuthorName: "AuthorName",
  UppercaseName: "Name",
  UppercaseUsername: "Username",
  UppercaseEmail: "Email",
  Data: "data",
  Result: "result",
  Payload: "payload",
  Page: "page",
  Limit: "limit",
  Posts: "posts",
  Items: "items",
  Body: "body",
  UppercaseBody: "Body",
  Content: "content",
  UppercaseContent: "Content",
  Caption: "caption",
  Text: "text",
  Title: "title",
  UppercaseTitle: "Title",
  Tags: "tags",
  UppercaseTags: "Tags",
  CreatedAt: "createdAt",
  SnakeCaseCreatedAt: "created_at",
  UppercaseCreatedAt: "CreatedAt",
  Votes: "votes",
  UppercaseVotes: "Votes",
  Likes: "likes",
  UppercaseLikes: "Likes",
  LikeCount: "likeCount",
  SnakeCaseLikeCount: "like_count",
  UppercaseLikeCount: "LikeCount",
  LikesCount: "LikesCount",
  Voted: "voted",
  UppercaseVoted: "Voted",
  Liked: "liked",
  IsLiked: "isLiked",
  SnakeCaseIsLiked: "is_liked",
  UppercaseIsLiked: "IsLiked",
  IsVoted: "IsVoted",
  CommentCount: "commentCount",
  SnakeCaseCommentCount: "comment_count",
  UppercaseCommentCount: "CommentCount",
  CommentsCount: "CommentsCount",
  LowercaseCommentsCount: "commentsCount",
  SnakeCaseCommentsCount: "comments_count",
  Comments: "comments",
  CommentId: "commentId",
  SnakeCaseCommentId: "comment_id",
  UppercaseCommentId: "CommentID",
  ParentId: "parentId",
  SnakeCaseParentId: "parent_id",
  UppercaseParentId: "ParentID",
  Author: "author",
  UppercaseAuthor: "Author",
  UppercaseUser: "User",
  Replies: "replies",
  UppercaseReplies: "Replies",
  PostCount: "post_count",
  CamelCasePostCount: "postCount",
  UppercasePostCount: "PostCount",
  SnakeCaseProfileLikeCount: "like_count",
  CamelCaseProfileLikeCount: "likeCount",
  ProfileLikeCount: "LikeCount",
  SnakeCaseProfileCommentCount: "comment_count",
  CamelCaseProfileCommentCount: "commentCount",
  ProfileCommentCount: "CommentCount",
} as const;

export type ApiField =
  (typeof API_FIELDS)[keyof typeof API_FIELDS];

export const API_ERROR_FIELDS = [
  API_FIELDS.Error,
  API_FIELDS.Message,
] as const;

export const API_NESTED_RESPONSE_CONTAINERS = [
  API_FIELDS.Data,
  API_FIELDS.Result,
  API_FIELDS.Payload,
] as const;
